### ISSUE TITLE
endpoint go wrong.

### ISSUE THREAD

**Issue by ardencod3** [orangewise/s3-files#10]
I ran out to get this error

`Hostname/IP doesn't match certificate's altnames: "Host: my-bucket-name.s3.s3-eu-west-1.amazonaws.com. is not in the cert's altnames: DNS:s3-eu-west-1.amazonaws.com, DNS:*.s3-eu-west-1.amazonaws.com, DNS:s3.eu-west-1.amazonaws.com, DNS:*.s3.eu-west-1.amazonaws.com, DNS:s3.dualstack.eu-west-1.amazonaws.com, DNS:*.s3.dualstack.eu-west-1.amazonaws.com, DNS:*.s3.amazonaws.com"`

look like it always insert .s3. between my bucket name and region. so I tested by force set the endpoint to  "my-bucket-name.s3-eu-west-1.amazonaws.com" and it work!

so my work around for now is set some option to override endpoint like this.
  
AWS.config.update({
    region: opts.region,
    endpoint: opts.region + '.amazonaws.com' //this line
  });

**Comment by orangewise** [comment]
Hi @ardencod3, thanks for the feedback. I don't think this is an issue with this module but more with the aws sdk/your setup. Have not seen this problem before.

**Comment by ardencod3** [comment]
Didn't look at aws backend setting yet but yes I think you are right. this issue is some where out side the module
