### ISSUE TITLE
Not able to access files

### ISSUE THREAD

**Issue by navjotdhanawat** [orangewise/s3-files#11]
How can we provide AWS credentials.

I am getting below error while fetching files.
CredentialsError: Missing credentials in config

**Comment by orangewise** [comment]
Hi @navjotdhanawat, did you try this: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/configuring-the-jssdk.html

**Comment by navjotdhanawat** [comment]
I had use AWS.config.update()
AWS.config.update({
    'region': region,
    'accessKeyId': accessKeyId,
    'secretAccessKey': secretAccessKey
  });

Before using a plugin. But not able to work. Still getting an error.

**Comment by orangewise** [comment]
Strange, works for me. Maybe you can try to set your credentials in environment vars...
