### ISSUE TITLE
Unable to download files from root directory of the bucket

### ISSUE THREAD

**Issue by djambrecina** [orangewise/s3-files#4]
When "" passed as folder parameter (root directory of the bucket), createKeyStream returns null.
"/" and "./" also doesn't work.

**Comment by orangewise** [comment]
Hi @djambrecina, a new version of this module has been released that can do this. Take a look at the readme https://github.com/orangewise/s3-files#usage-stream-files-from-the-root-of-a-bucket

Cheers!
